spring:
  # docker run -d -e POSTGRES_PASSWORD=admin -p 5432:5432 postgres
  datasource:
    url: ${DATASOURCE_URL:jdbc:postgresql://localhost:5432/customer}
    username: ${DATASOURCE_USERNAME:postgres}
    password: ${DATASOURCE_PASSWORD:admin}
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true
  autoconfigure:
    exclude: org.springframework.boot.autoconfigure.data.redis.RedisAutoConfiguration
