server:
  port: 8080

base:
  packages: com.microservice.framework

spring:
  autoconfigure:
    exclude: org.springframework.boot.autoconfigure.data.redis.RedisAutoConfiguration
  cloud:
    consul:
      discovery:
        heartbeat:
          enabled: true
          ttl: 10s