spring:
  # docker run -d -e POSTGRES_PASSWORD=admin -p 5432:5432 postgres
  datasource:
    url: ${DATASOURCE_URL:jdbc:postgresql://localhost:5432/inventory}
    username: ${DATASOURCE_USERNAME:postgres}
    password: ${DATASOURCE_PASSWORD:admin}
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true
  #  docker run -p 16379:6379 -d redis:6.0 redis-server --requirepass "mypass"
  data:
    redis:
      host: localhost
      port: 16379
      password: mypass
