spring:
  application:
    name: order-service
# docker run -detach --env MYSQL_ROOT_PASSWORD=root_password --env MYSQL_USER=user --env MYSQL_PASSWORD=password --env MYSQL_DATABASE=database --name mysql --publish 3306:3306 mysql:8-oracle
  datasource:
    url: jdbc:mysql://localhost:3306/order
    username: root
    password: dummypassword
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect
        format_sql: true
#  docker run -p 16379:6379 -d redis:6.0 redis-server --requirepass "mypass"
  data:
    redis:
      host: localhost
      port: 16379
      password: mypass
